import type { ComponentType, SVGProps } from 'react';
import {
  AdjustmentsHorizontalIcon,
  ArchiveBoxIcon,
  ArrowLeftIcon,
  ArrowPathIcon,
  ArrowRightIcon,
  ArrowTopRightOnSquareIcon,
  ArrowUpTrayIcon,
  ArrowsPointingOutIcon,
  BoltIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDownIcon,
  CircleStackIcon,
  ClipboardIcon,
  ClockIcon,
  CodeBracketIcon,
  CommandLineIcon,
  ComputerDesktopIcon,
  DocumentIcon,
  DocumentTextIcon,
  ExclamationTriangleIcon,
  EyeIcon,
  EyeSlashIcon,
  FilmIcon,
  FolderIcon,
  InformationCircleIcon,
  KeyIcon,
  MagnifyingGlassIcon,
  MinusIcon,
  MoonIcon,
  MusicalNoteIcon,
  PaintBrushIcon,
  PlusIcon,
  PhotoIcon,
  PresentationChartLineIcon,
  QueueListIcon,
  ShieldCheckIcon,
  Squares2X2Icon,
  SunIcon,
  TableCellsIcon,
  TrashIcon,
  XCircleIcon,
  XMarkIcon,
} from '@heroicons/react/24/outline';
import type { FileKind } from '@/core/domain/types';

type IconComponent = ComponentType<SVGProps<SVGSVGElement>>;

const ICONS: Record<string, IconComponent> = {
  grid: Squares2X2Icon,
  queue: QueueListIcon,
  history: ClockIcon,
  tune: AdjustmentsHorizontalIcon,
  shield: ShieldCheckIcon,
  eye: EyeIcon,
  eyeOff: EyeSlashIcon,
  minimize: MinusIcon,
  minus: MinusIcon,
  plus: PlusIcon,
  maximize: ArrowsPointingOutIcon,
  close: XMarkIcon,
  upload: ArrowUpTrayIcon,
  folder: FolderIcon,
  back: ArrowLeftIcon,
  arrow: ArrowRightIcon,
  trash: TrashIcon,
  copy: ClipboardIcon,
  external: ArrowTopRightOnSquareIcon,
  check: CheckIcon,
  alert: ExclamationTriangleIcon,
  refresh: ArrowPathIcon,
  search: MagnifyingGlassIcon,
  brush: PaintBrushIcon,
  key: KeyIcon,
  bolt: BoltIcon,
  doc: DocumentTextIcon,
  file: DocumentIcon,
  archive: ArchiveBoxIcon,
  image: PhotoIcon,
  video: FilmIcon,
  audio: MusicalNoteIcon,
  code: CodeBracketIcon,
  executable: CommandLineIcon,
  spreadsheet: TableCellsIcon,
  presentation: PresentationChartLineIcon,
  database: CircleStackIcon,
  sun: SunIcon,
  moon: MoonIcon,
  monitor: ComputerDesktopIcon,
  chevron: ChevronDownIcon,
  info: InformationCircleIcon,
  success: CheckCircleIcon,
  danger: XCircleIcon,
};

const FILE_KIND_ICON: Record<FileKind, string> = {
  folder: 'folder',
  archive: 'archive',
  image: 'image',
  video: 'video',
  audio: 'audio',
  code: 'code',
  executable: 'executable',
  document: 'doc',
  spreadsheet: 'spreadsheet',
  presentation: 'presentation',
  font: 'doc',
  disk: 'archive',
  database: 'database',
  text: 'doc',
  unknown: 'file',
};

export function fileIconName(kind?: FileKind): string {
  return FILE_KIND_ICON[kind ?? 'unknown'] ?? 'file';
}

export function Icon({ name }: { name: string }) {
  const IconComponent = ICONS[name] ?? Squares2X2Icon;
  return <IconComponent className="glyph" aria-hidden="true" />;
}
